version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile/frontend.Dockerfile
    container_name: frontend
    hostname: sample-app
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    entrypoint: "sh"
    stdin_open: true
    tty: true
